mport turtle

turtle = turtle.Turtle()

def finishFlag(x, y):
  turtle.up()
  turtle.goto(x, y)
  turtle.setheading(0)
  turtle.down()
  turtle.color("black")
  turtle.forward(120)
  turtle.right(90)
  turtle.forward(60)
  turtle.right(90)
  turtle.forward(120)
  turtle.right(90)
  turtle.forward(60)
  turtle.right(90)
  
def flag3Bar(x, y, colorTop, colorMiddle, colorBottom):
  turtle.up()
  turtle.goto(x, y-40)
  turtle.setheading(0)
  turtle.down()
  turtle.color(colorBottom)
  turtle.fillcolor(colorBottom)
  turtle.begin_fill()
  turtle.forward(120)
  turtle.right(90)
  turtle.forward(20)
  turtle.right(90)
  turtle.forward(120)
  turtle.right(90)
  turtle.forward(20)
  turtle.end_fill()
  turtle.forward(20)
  turtle.right(90)
  turtle.color(colorMiddle)
  turtle.fillcolor(colorMiddle)
  turtle.begin_fill()
  turtle.forward(120)
  turtle.right(90)
  turtle.forward(20)
  turtle.right(90)
  turtle.forward(120)
  turtle.right(90)
  turtle.forward(20)
  turtle.end_fill()
  turtle.forward(20)
  turtle.right(90)
  turtle.color(colorTop)
  turtle.fillcolor(colorTop)
  turtle.begin_fill()
  turtle.forward(120)
  turtle.right(90)
  turtle.forward(20)
  turtle.right(90)
  turtle.forward(120)
  turtle.right(90)
  turtle.forward(20)
  turtle.end_fill()
  finishFlag(x, y)

def flag3Column(x, y, colorLeft, colorMiddle, colorRight):
  turtle.up()
  turtle.goto(x, y)
  turtle.setheading(0)
  turtle.down()
  turtle.color(colorLeft)
  turtle.fillcolor(colorLeft)
  turtle.begin_fill()
  turtle.forward(40)
  turtle.right(90)
  turtle.forward(60)
  turtle.right(90)
  turtle.forward(40)
  turtle.right(90)
  turtle.forward(60)
  turtle.end_fill()
  turtle.right(90)
  turtle.forward(40)
  turtle.color(colorMiddle)
  turtle.fillcolor(colorMiddle)
  turtle.begin_fill()
  turtle.forward(40)
  turtle.right(90)
  turtle.forward(60)
  turtle.right(90)
  turtle.forward(40)
  turtle.right(90)
  turtle.forward(60)
  turtle.end_fill()
  turtle.right(90)
  turtle.forward(40)
  turtle.color(colorRight)
  turtle.fillcolor(colorRight)
  turtle.begin_fill()
  turtle.forward(40)
  turtle.right(90)
  turtle.forward(60)
  turtle.right(90)
  turtle.forward(40)
  turtle.right(90)
  turtle.forward(60)
  turtle.end_fill()
  finishFlag(x, y)


def flagGermany(x, y):
  flag3Bar(x, y, "black","red","gold")

def flagAustria(x, y):
  flag3Bar(x, y, "red","white","red")

def flagItaly(x, y):
  flag3Column(x, y, "green","white","red")

def flagFrance(x, y):
  flag3Column(x, y, "darkblue","white","red")


flagItaly(-100, 100)
flagFrance(100, 100)
flagAustria(-100, 0)
flagGermany(100, 0)
